language: go
sudo: false
go:
  - 1.5
  - tip

env:
  - GOARCH=amd64

script:
  - go version
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go test -v -covermode=count -coverprofile=coverage.out *.go

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken NtrV5eEKgeQCz3F0do52oQVxjKQBxbzoq

notifications:
  email: false
