version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\wookay\aheui-go

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get github.com/stretchr/testify/assert
  - go get -v -t ./...

build_script:
  - go test -v ./...
